task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ["bbox"]

num_classes: 20

train_dataloader:
  type: DataLoader
  dataset:
    type: VOCDetection
    root: ./dataset/voc/VOCdevkit/VOC2007/
    ann_file: trainval.txt
    label_file: label_list.txt
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 2
  batch_size: 8
  drop_last: True
  collate_fn:
    type: BatchImageCollateFuncion

val_dataloader:
  type: DataLoader
  dataset:
    type: VOCDetection
    root: ./dataset/voc/VOCdevkit/VOC2007/
    ann_file: test.txt
    label_file: label_list.txt
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 2
  batch_size: 16
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
